services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marcador_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_TCP_PORT=1435
    ports:
      - "1435:1435"
    volumes:
      - ./db:/db
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1435", "-C", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 30
    profiles: ["db", "all"]

  db_init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marcador_db_init
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - ./db:/db
      - ./scripts:/scripts
    entrypoint: ["/bin/bash","/scripts/db-init.sh"]   # evita problemas de permisos en Windows
    restart: "no"
    profiles: ["db", "all"]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: marcador_api
    depends_on:
      db:
        condition: service_healthy
      db_init:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - DB_CONNECTION_STRING=Server=db,1435;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRES_MINUTES=${JWT_EXPIRES_MINUTES}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    profiles: ["api", "all"]

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: marcador_ui
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4200:80"
    profiles: ["ui", "all"]

  proxy:
    image: nginx:alpine
    container_name: marcador_proxy
    depends_on:
      - api
      - ui
    ports:
      - "80:80"
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
    profiles: ["proxy", "all"]
